# Wallpaper inicial. Cambia esta ruta cuando quieras.
# Si la imagen no existe, hyprpaper simplemente no pondrá fondo.
# preload = ~/Pictures/wallpaper.jpg
# wallpaper = ,~/Pictures/wallpaper.jpg
splash = false
